"""Criando tabela de posts

Revision ID: 0f9943db2bd0
Revises: 6792338c07bb
Create Date: 2025-04-03 05:45:08.799470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f9943db2bd0'
down_revision = '6792338c07bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('rich_text', sa.Text(), nullable=False),
    sa.Column('banner_img_src', sa.String(length=255), nullable=True),
    sa.Column('post_type', sa.Enum('blog', 'article', 'ebd', name='post_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
